# This is where application configuration goes.

spring.application.name=postcode-service

# This is for DB connection.
spring.datasource.url=jdbc:postgresql://localhost:5432/postcode_service
spring.datasource.username=cheah
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Let spring boot to log in ECS format: structured JSON.
logging.structured.format.console=ecs

# For spring security via env variables.
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}